# Generated by ard-make version 1.2
ARDUINO_DIR = /opt/arduino-1.8.19
#AVR_TOOLS_DIR=$(ARDUINO_DIR)/hardware/tools/avr-sleepypi/
ARDMK_DIR=/usr/share/arduino
USER_LIB_PATH=/home/pi/Arduino/libraries
ARDUINO_LIBS=Seeed_Arduino_CAN SPI Wire SleepyPi2 PCF8523 Time LowPower PinChangeInterrupt EEPROM

# Build Options
#CXXFLAGS_STD += -fno-lto -fno-threadsafe-statics -Wall
CXXFLAGS_STD += -fno-threadsafe-statics -Wall -std=gnu++11 -flto -fno-fat-lto-objects

BOARD_TAG = fio
MONITOR_PORT = /dev/ttyS0

include $(ARDMK_DIR)/Arduino.mk
