# Generated by ard-make version 1.2
ARDUINO_DIR = /opt/arduino/arduino-1.8.19
ARDMK_DIR=/usr/share/arduino
USER_LIB_PATH=/home/jacob/Arduino/libraries
ARDUINO_LIBS=Seeed_Arduino_CAN SPI Wire CANSerial SleepyPi2 PCF8523 Time LowPower PinChangeInterrupt EEPROM

# Build Options
CXXFLAGS_STD += -fno-threadsafe-statics -Wall

BOARD_TAG = fio
MONITOR_PORT = /dev/ttyUSB0

include $(ARDMK_DIR)/Arduino.mk
