# Generated by ard-make version 1.2
ARDUINO_DIR=/opt/arduino-1.8.8/
ARDMK_DIR=/usr/share/arduino
AVR_TOOLS_DIR=/opt/arduino-1.8.8/hardware/tools/avr-sleepypi/

BOARD_TAG = fio
MONITOR_PORT = /dev/ttyS0

include $(ARDMK_DIR)/Arduino.mk
